import { SelectOptionModel } from '../models/options';

export const MUNICIPALITIES: SelectOptionModel[] = [
  'ABEJORRAL',
  'ABRIAQUI',
  'ALEJANDRIA',
  'AMAGA',
  'AMALFI',
  'ANDES',
  'ANGELOPOLIS',
  'ANGOSTURA',
  'ANORI',
  'ANZA',
  'APARTADO',
  'ARBOLETES',
  'ARGELIA',
  'ARMENIA',
  'BARBOSA',
  'BELLO',
  'BELMIRA',
  'BETANIA',
  'BETULIA',
  'BRICEÑO',
  'BURITICA',
  'CACERES',
  'CAICEDO',
  'CALDAS',
  'CAMPAMENTO',
  'CARACOLI',
  'CARAMANTA',
  'CAREPA',
  'CAROLINA',
  'CAUCASIA',
  'CAÑASGORDAS',
  'CHIGORODO',
  'CISNEROS',
  'CIUDAD BOLIVAR',
  'COCORNA',
  'CONCEPCION',
  'CONCORDIA',
  'COPACABANA',
  'DABEIBA',
  'DONMATIAS',
  'EBEJICO',
  'EL BAGRE',
  'EL CARMEN DE VIBORAL',
  'EL SANTUARIO',
  'ENTRERRIOS',
  'ENVIGADO',
  'FREDONIA',
  'FRONTINO',
  'GIRALDO',
  'GIRARDOTA',
  'GOMEZ PLATA',
  'GRANADA',
  'GUADALUPE',
  'GUARNE',
  'GUATAPE',
  'HELICONIA',
  'HISPANIA',
  'ITAGÜI',
  'ITUANGO',
  'JARDIN',
  'JERICO',
  'LA CEJA',
  'LA ESTRELLA',
  'LA PINTADA',
  'LA UNION',
  'LIBORINA',
  'MACEO',
  'MARINILLA',
  'MEDELLIN',
  'MONTEBELLO',
  'MURINDO',
  'MUTATA',
  'NARIÑO',
  'NECHI',
  'NECOCLI',
  'OLAYA',
  'PEQUE',
  'PEÑOL',
  'PUEBLORRICO',
  'PUERTO BERRIO',
  'PUERTO NARE',
  'PUERTO TRIUNFO',
  'REMEDIOS',
  'RETIRO',
  'RIONEGRO',
  'SABANALARGA',
  'SABANETA',
  'SALGAR',
  'SAN ANDRES DE CUERQUIA',
  'SAN CARLOS',
  'SAN FRANCISCO',
  'SAN JERONIMO',
  'SAN JOSE DE LA MONTAÑA',
  'SAN JUAN DE URABA',
  'SAN LUIS',
  'SAN PEDRO DE LOS MILAGROS',
  'SAN PEDRO DE URABA',
  'SAN RAFAEL',
  'SAN ROQUE',
  'SAN VICENTE FERRER',
  'SANTA BARBARA',
  'SANTA FE DE ANTIOQUIA',
  'SANTA ROSA DE OSOS',
  'SANTO DOMINGO',
  'SEGOVIA',
  'SONSON',
  'SOPETRAN',
  'TAMESIS',
  'TARAZA',
  'TARSO',
  'TITIRIBI',
  'TOLEDO',
  'TURBO',
  'URAMITA',
  'URRAO',
  'VALDIVIA',
  'VALPARAISO',
  'VEGACHI',
  'VENECIA',
  'VIGIA DEL FUERTE',
  'YALI',
  'YARUMAL',
  'YOLOMBO',
  'YONDO',
  'ZARAGOZA',
  'OTRO MUNICIPIO',
].map((item, index) => {
  return {
    id: index + 1,
    value: item,
  };
});

export const DOCUMENT_TYPES: SelectOptionModel[] = [
  {
    id: 1,
    value: 'TI',
    description: 'Tarjeta de identidad',
  },
  {
    id: 2,
    value: 'CC',
    description: 'Cédula de ciudadanía',
  },
  {
    id: 3,
    value: 'TE',
    description: 'Tarjeta de extranjería',
  },
  {
    id: 4,
    value: 'CE',
    description: 'Cédula de extranjería',
  },

  {
    id: 5,
    value: 'PP',
    description: 'Pasaporte',
  },
];

export const SECTOR_TYPES: SelectOptionModel[] = [
  {
    id: 1,
    value: 'Sector 1',
    description: 'Sector 1',
  },
  {
    id: 2,
    value: 'Sector 2',
    description: 'Sector 2',
  },
  {
    id: 3,
    value: 'Sector 3',
    description: 'Sector 3',
  },
  {
    id: 4,
    value: 'Sector 4',
    description: 'Sector 4',
  },
  {
    id: 5,
    value: 'Sector 5',
    description: 'Sector 5',
  },
];
